### ISSUE TITLE
MarshalLog() does not marshal slices or maps

### ISSUE THREAD

**Issue by MadVikingGod** [go-logr/logr#131]
I don't know if this is appropriate here or it should be an issue in each of the adapters.

When you have a type that implements the `Marshaler` interface logr will take the expected action and Marshal the type before sending it to the sink.  If you have a Marshaler in a slice, map, or object logr will **not** marshal this type before sending it.  

This means that different adapters (zapr, logrusr etc) are marshaling the object at different levels.  For example, `stdr` will recursively unmarshal and get the expected behavior, but I would have to implement zap's/logrus's Marshaler interface to have the same effect.  I created a [gist](https://gist.github.com/MadVikingGod/bb04c40e654602e173934180c691d645), and a [playground](https://go.dev/play/p/VkejC8f5_sP) that demonstrates this.

What I expect to happen is that the object eventually sent to the sink would be unmarshaled uniformly across all adapters. So from my example:
stdr would output:
```
2009/11/10 23:00:00 "level"=0 "msg"="slice" "y"=[{"Value":2},{"Value":3}]
```
And zap would output:
```
{"level":"info","msg":"slice","y":[{"Value":2},{"Value":3}]}
```

**Comment by pohly** [comment]
`logr` itself doesn't handle the `Marshaler` interface, that's all done in the sink while it serializes key/value pairs. This is still a good place to discuss the expected behavior as guidance for implementers and users.

I filed a similar issue against zapr a while back: https://github.com/go-logr/zapr/issues/45.

The conclusion at the time was that it's simply how zap works: interfaces are checked by `zap.Any`, but not anymore once a type is determined to need reflection. We could have asked for changes, but the zap authors probably wanted it to work like that.

For `logr.Marshaler` we don't have a choice: zapr can check for it before once before handing the final value to zap, but zap itself then won't know about this logr interface and thus ignore it. We could add special support for some cases (for example, slices), but that still wouldn't cover slices that occur as field.

**Comment by thockin** [comment]
FWIW, `github.com/go-logr/logr/funcr` should do the right thing.

I don't think this is something we can really fix in logr
