### ISSUE TITLE
logr cannot log struct fields which are not exposed

### ISSUE THREAD

**Issue by unmarshall** [go-logr/logr#142]
Hello,

In the below example i am using logr in combination with zap.

```go
type nameValue struct {
   name string
   value int
}

// create a instance of this and try and log it
func main() {
    logger := logr.New(zap.New(zap.UseFlagOptions(&zap.Options)).GetSink())
    n := nameValue {
        name: "bingo",
        value: 10,
    }
    logger.V(2).Info("testing logging for nameValue", "nameValue", n)
}
```

This will print the following to the stdout: 
> testing logging for nameValue "nameValue": "{}"

Assumption made is that if you do not expose fields in a struct then you should also not print it out in logs. In general i agree but it seems too harsh a decision as you can enable debug logs and then get more detailed logs which also print the non-exposed fields of the struct (in other words it does not filter out unless explicitly coded for via `MarshalLog`).

I even wrote a `String` method (Stringer interface), which words when logging a single instance of the struct but when you have a `slice` of struct with un-exposed fields then it again prints out `{}` empty pair of curly braces. The only way to circumvent this behavior is therefore to directly use `fmt.Sprintf` and create a log message which beats the purpose of having a logging framework in the first place.

Also when native `fmt` package can easily print structs via `%v` and its variants then why should a logging framework be more restrictive than what golang natively provides? Also exposing fields just so that they can be logged is not a valid argument to expose them when there is no other package that requires it.

I would like to know if there are still better ways to achieve this and your reasoning for the current behavior.

Best Regards,
Madhav

**Comment by unmarshall** [comment]
> What is this zap package in your example?

"sigs.k8s.io/controller-runtime/pkg/log/zap"

**Comment by pohly** [comment]
Directly depending on zap won't help. It is *zap*, not github.com/go-logr/zapr or github.com/go-logr/logr, which doesn't log the internal fields. There is some logic in zapr around handling of zap.Field and logr.Marshaler, but for your case it is zap.Any which does the actual work:

https://github.com/go-logr/zapr/blob/df10f4788c061a53564cebafc055fd9ad3f3255e/zapr.go#L100-L178

The underlying problem is that access to unexported fields is limited via reflection. `fmt.Printf` gets around that limitation - probably it uses APIs that are not available outside of the standard library, or it uses tricks like the one from https://stackoverflow.com/questions/42664837/how-to-access-unexported-struct-fields

One option would be to use klogr as backend with text output. That uses `fmt.Sprintf("%+v")` for structs and thus shows unexported fields. But it cannot produce JSON.

Another option would be an option in zapr which tells it to use `fmt.Sprintf("%+v")` and thus strings for structs. This looks like a hack to me.

You can also file an issue against https://github.com/uber-go/zap. Perhaps they can do something about it.

**Comment by unmarshall** [comment]
> One option would be to use klogr as backend with text output. That uses fmt.Sprintf("%+v") for structs and thus shows unexported fields. But it cannot produce JSON.

True, that is what we have used in the current setup. So instead of using the recommended key-value pairs that get set for every structured log we just have a pre-formatted message via `fmt.Sprintf` which works but as you state is no longer structured.

>You can also file an issue against https://github.com/uber-go/zap. Perhaps they can do something about it.

Yes, let me try raising an issue there as well and hope that allow it so that `zapr` can then be enhanced to provide this out of the box. Since nothing can be done in `logr` i would then close this issue.
