### ISSUE TITLE
WithValues with the same key repeats the field

### ISSUE THREAD

**Issue by gshirazi** [go-logr/logr#170]
```
log = log.WithValues("k", "v1")
log = log.WithValues("k", "v2")
```

I would expect that resulting log contain only {"k": "v2"} but it contains both {"k": "v1" , "k": "v2"}. How to de-duplicate?

**Comment by pohly** [comment]
This needs to be implemented by the logger implementation. Which one are you using?

**Comment by gshirazi** [comment]
zapr

**Comment by pohly** [comment]
zapr just hands over to the upstream zap logger: https://github.com/go-logr/zapr/blob/48df242fffb25049c72e208aea4826177ff5fe8e/zapr.go#L222

I don't think we should override how zap handles this, so if you absolutely need this fixed, you should file an upstream issue: https://github.com/uber-go/zap/issues

However, it might be intentional. Finding duplicates has a performance impact, and it's mostly cosmetic because a JSON parser will only consider the most recent value, so `{"k": "v1" , "k": "v2"}` and `{ "k": "v2"}` are equivalent.

**Comment by gshirazi** [comment]
Got it, thanks a lot for explaination.
