### ISSUE TITLE
Context support

### ISSUE THREAD

**Issue by iand** [go-logr/logr#25]
One common pattern for logging is to pass the current logging context to called functions and types using a Go context. This decouples much of the program from a specific implementation of the logr interface. This is similar to adding a logger argument to every function but is more general since it allows non logr-aware packages to pass contexts through to logr-aware packages.

A suggested API (these are top level functions):

```Go
// FromContext returns a logr.Logger constructed from the context or returns a null logger if no
// logger details are found in the context.
func FromContext(ctx context.Context) logr.Logger

// NewContext returns a new context that embeds the logger.
func NewContext(ctx context.Context, l logr.Logger) context.Context
```

This can already be implemented in a separate package (I created [logctxr](https://github.com/iand/logctxr) as an example) but I thought it would be worth considering as a core addition to the `logr` package.

*Updated 2020-10-20 to remove NewLogger function based on discussion*

**Comment by thockin** [comment]
I think I'd leave out the NewLogger bit, but I think I'd take the rest - PRs welcome!!

**Comment by wojas** [comment]
If accepted, the `NewLogger` should indeed be left out, because conflicting implementations could end up overwriting it in a big project. 

Now there is the question of what to return from `FromContext` if no logger was set on the context. Returning some kind of `NullLogger` is probably the best approach here, but it could potentially make it harder to figure out why no logging output is returned. But I think this is better than requiring every piece of code that wants to use this to explicitly handle this and create a `NullLogger` themselves.

I personally prefer to pass `logr.Logger` around explicitly, but this can be useful to add modular logging to places that currently use a global logger without having to add all the plumbing to pass it down explicitly. Often a context is already available in this code.

**Comment by thockin** [comment]
What is the norm for context?  To return nil and let callers know, or to
NullLogger it out, or to panic()?  It seems easiest to just return nil -
callers will explode and I think they should.  It's either truly sa
guarantee of the call-stack (in which case I want to know it was broken) or
it is truly optional (in which case I really *should* be making my own
decision about it.

**Comment by xuyang2** [comment]
How about
```go
// panics
func MustFromContext(ctx context.Context) logr.Logger
```

**Comment by thockin** [comment]
What do other libs do wrt context?  The context docs suggest FrommContext

**Comment by wojas** [comment]
The way I see it a `FromContext` serves two purposes:

1. It eliminates the need to pass the Logger around explicitly. A context is often already available or nearby on the call stack.
2. It provides a convenient way for an independent component to provide logging when the caller wants it to log.

If no logger is set on the context, the best way to handle it would be to provide a `NullLogger`, as the caller is apparently not interested in logging the output of this component.

In these cases it is unlikely that this independent component would want to do some alternative way of logging as a fallback. More likely a component with a strong opinion on logging would provide additional options to configure logging and these would be used in preference to any logger configured in the context. 

I do not think that returning a `nil` value would be a good idea, because the only reasonable way a component can handle it is by not logging, which is exactly what the `NullLogger` would do without the inconvenience of the caller having to set this up explicitly. A panic would be even worse, because you can have your program panic just because some hidden variable is not available on a context that could come from anywhere. And since this code path may not be run on init, it could happen at runtime in production, just because it could not log some details in case it would be interested in doing so.

**Comment by thockin** [comment]
If I have a component that wants to log, and I don't want it to, I can
provide a NullLogger (and maybe logr should include a NullLogger
implementation, or we should make a new repo for that).  But if I don't
specify ANYTHING I think it is a contract failure, and we should not simply
hide it.

If you have to fail, fail obviously.

It is morally equivalent to passing nil when the callee expects a valid
object in an argument.  Nobody would argue that the runtime should inject a
fake object.

Now, one could argue that context is TERRIBLE for this - precisely because
the "contract" is less obvious and less well enforced.

No magic please.

**Comment by wojas** [comment]
The magic aspect is indeed the disadvantage of using a context for this. Clearly explicitly passing the object would more clearly communicate the contract and it would have my preference in most cases for new code.

But accepting the context approach would make it easier to support debug logging without API changes for components that perhaps now are using global loggers, which is also implicit behavior. Kubernetes uses this approach all over the place.

If a `FromContext` is added that does not always return a usable object, it should not return this in-band as a nil return value, but instead have a signature like this:

```go
func FromContext(ctx context.Context) (logr.Logger, error)
```

See https://github.com/golang/go/wiki/CodeReviewComments#in-band-errors

But I don't see any advantage in implementing it without a guaranteed to be usable return object.

**Comment by iand** [comment]
> If no logger is set on the context, the best way to handle it would be to provide a `NullLogger`, as the caller is apparently not interested in logging the output of this component.

This is the reply I was going to make while thinking about it on my walk today.

I wrote a Null implementation which I am happy to contribute (or someone can take - it's PD) https://github.com/iand/logfmtr/blob/master/logfmtr.go#L392

**Comment by wojas** [comment]
@iand A `NullLogger` should never panic, it should just return itself in each of the methods that return a new logger.

I also have one lying around, since I need it all the time as a default logger if none is passed in through options:

```go
type nullLogger struct{}

func (n nullLogger) Enabled() bool {
	return false
}

func (n nullLogger) Info(msg string, keysAndValues ...interface{}) {
}

func (n nullLogger) Error(err error, msg string, keysAndValues ...interface{}) {
}

func (n nullLogger) V(level int) logr.Logger {
	return n
}

func (n nullLogger) WithValues(keysAndValues ...interface{}) logr.Logger {
	return n
}

func (n nullLogger) WithName(name string) logr.Logger {
	return n
}
```

**Comment by iand** [comment]
@wojas yes I agree. I forgot my implementation panics because the loggers are lazily configured and I wanted to be explicit to the user that they should not expect their null logger to work in that way.

**Comment by wojas** [comment]
I proposed adding such a null logger in #26, since it's useful anyway.

**Comment by iand** [comment]
I updated the proposal to remove the NewLogger function

**Comment by thockin** [comment]
I did some searching on github for other definitions of FromContext.  The vast majority just return the type with no success indicator.  A smaller number return (value, ok).

In this case, the OK seems redundant since we KNOW that the type returned is an interface, so `nil` means the same this as ok=false.

I think the contract here should be "returns the context's Logger or nil if no Logger is in the context".  Clients which expect a Logger should say so and make callers provide one.  I know DI is not really Go-ish, but it has saved my butt many times.

**Comment by thockin** [comment]
If you send a PR we can carry on there, or I can do it if you don't want to for whatever reason

**Comment by wojas** [comment]
The review comment about in-band errors still apply:  https://github.com/golang/go/wiki/CodeReviewComments#in-band-errors

An explicit error (or ok) return value makes clear that an operation can fail. Not having an explicit return value that must be handled or ignored sets up a minefield where packages may assume it always returns a useable value (as it always may have one in their environment), but then panic when the module tries to log due to a nil value. Since actual logging may only happen in production during actual request handling, this can cause a lot of pain.

If the caller must check it anyway, why not make that explicit with a return value?

I still believe that returning a null logger would be a more sensible behavior in this case, and returning usable zero values is a pattern that is found in many places in Go. Perhaps with some mechanism to check if this is a null logger for code that actually cares?

**Comment by thockin** [comment]
The *only* error that can be returned is "no logger registered" so the results will literally *always* be either `logger, nil` or `nil, "no logger"`.  The cost is that every caller changes from:

```
logger := logr.FromContext(ctx)
// use logger (if it is nil, crash)
```

or

```
logger := logr.FromContext(ctx)
if logger == nil {
    // do something
}
// use logger
```

into 

```
logger, _ := logr.FromContext(ctx)
if logger == nil {
    // do something
}
// use logger
```

or 

```
logger, err := logr.FromContext(ctx)
if err != nil {
    // do something
}
// use logger (if it is nil, crash)
```

or worse:

```
logger, err := logr.FromContext(ctx)
if err != nil || logger == nil {
    // do something
}
// use logger
```

I understand the self-documentation point, but isn't the fact that it can be nil just as obvious?  Are there other hypothetical errors that could be returned?

If a lib wants the NullLogger behavior, it can always capture the above in its own space and "do something" becomes "create a null logger".

Or we could add simple FromContext() *and* FromContextOrNull() which does what you describe, I guess.

**Comment by thockin** [comment]
docker and containerd are app-owned.  It's completely reasonable for them to assume a default.

kayvee is a lib focused on doing work (i.e. not focused on logging) and as such it is making a decision what to do when the caller did not pass a logger (it goes to stderr).  I will come back to this one.

zap is a logging impl lib and maybe their decision is right? :)

hc-log is a logging-impl lib and so it makes sense to have a default, IMO.  logr is a logging API, not an impl.  If we were talking about glogr.FromContext() or zapr.FromContext() I would sing a different song.

Let's look at kayvee.  I think it supports my point.  It is a library that wants to log, but logging is not its primary purpose.  If the caller didn't pass a logger, they will write to stdout.

Assuming the logr effort was successful and kayvee adopted it, they have two paths to follow.

1) call `logr.FromContext()`
2) call `kayvee/logger.FromContext()`

If logr.FromContext() automatically returned a NullLogger, we would be _taking_away_ their ability to default to stderr.  To achieve their desired result, they NEED the `IsNull()` test.  So logr.FromContext() would be going out of its way to allocate an object and return it, only to have the caller discard that object and use their own.  We would have been better all around (in both paths) to just return nil, and let the library wrap-and-default if it needs to.

```
package myliblogger

func FromContext(ctx) logr.Logger {
    l := logr.FromContext(ctx)
    if l != nil {
        return l
    }
    return myOwnDefaultLogger()
}
```

**Comment by iand** [comment]
This is why my original proposal (and my example implementation ctxr) provided a NewLogger function. By default that could return nil but the user application could set it to a function that returns their preferred logger implementation.  (I didn't explain it too well so some comments here assumed each implementation would call it, but it should be the application when it is configuring its logger options on startup).

**Comment by thockin** [comment]
My experience with these sorts of global defaults is that they usually just make it harder to figure out, as opposed to the caller just doing the right thing.  That said, I'd be willing to entertain that as a different discussion :)

**Comment by wojas** [comment]
Not sure if the naming of `FromContextOrNull()` is clear enough, as people may mistake it for `FromContextOrNil()`. We may need better names, but in general just providing both options would not be a bad solution.

As for the usage examples, we would end up with two use cases (still using the proposed names for now):

#### Option 1: The caller does not want to bother with the exact logging and simply calls:

```go
l := logr.FromContextOrNull()
```

It then knows it can just log to the logger without worrying about anything else.

#### Option 2: The caller cares if a logger was set or not.

In this case the caller should always check the result. Just panicing if some magic context variable was not set does not sound like good behavior and we do not want to make it too easy for people to do this accidentally.

Given the nature of the check, a boolean result would probably be sufficient, as there is no more information to convey. It would usually lead to one of these two patterns:

```go
// Set a default if no logger was set
l, ok := logr.FromContext()
if !ok {
    l = createSomeDefaultLogger()
}
```

```go
// Error if no logger was set
l, ok := logr.FromContext()
if !ok {
    return errors.New("no logger")
}
```

The second case puts the burden of creating an error on the caller. I suspect that 90% of the calls will happen in a function that has an error return value.

This is why it's probably better to return an error, even though there is only one thing that can go wrong. 

Same with an error return value:

```go
// Set a default if no logger was set
l, err := logr.FromContext()
if err != nil {
    l = createSomeDefaultLogger()
}
```

```go
// Error if no logger was set
l, err := logr.FromContext()
if err != nil {
    return err
}
```

This approach does not make a big difference in the first case, but greatly simplifies the second.

I would argue that these examples are not canonical Go code:

- `if logger == nil`
- `if err != nil || logger == nil`

**Comment by wojas** [comment]
Regarding the naming , perhaps use `FromContext` and `FromContextOrDiscard`. This matches the `ioutil.Discard` writer name in the stdlib and is clearer about what it does for users not familiar with `/dev/null`.

We can rename the nullLogger and `Null()` function in PR #28 to `discardLogger` and `Discard()`.

**Comment by thockin** [comment]
I like `FromContextOrDiscard()` as a name.  I do not care for `Discard()` as a constructor but I will acquiesce to convention on that.

WRT `error` vs `bool` vs `nil` - I find all arguments about being idiomatic to be weak, at best.  But in the absence of a truly compelling reason to differ I will concede.  It's not worth further debate.  Especially as this API is not yet 1.0 (aka I reserve the right to change my mind when new information is available)
