### ISSUE TITLE
Consider standard Go module versioning (v2, v3...)

### ISSUE THREAD

**Issue by bandesz** [go-logr/logr#37]
## What

I bumped into an issue in my application that there were some dependencies using logr v0.1.0 and some v0.2.0, which might cause some errors.

Please consider using the standard Go module versioning, so it's possible to depend on multiple versions of this library.

See https://blog.golang.org/v2-go-modules for more details.

**Comment by thockin** [comment]
Right now it's pre-1.0.  I find Go's answer to v2 modules to be silly, but if/when we do need to break compat, we will consider it.

We're pressing for a 1.0 soonish

**Comment by iamnoah** [comment]
Wanted to bump this as the lack of a namespace for v1 is causing my team issues. e.g., 0.4.0 logr.FromContext is incompatible with v1. I don't really see what is silly about not breaking people.

**Comment by thockin** [comment]
Breaking people is bad, but this was documented as pre-1.0 because I feared we might need it.   Now that we are at 1.0, I will NOT break people.

I'm not sure I _can_ help you now.  It's tagged and I can't untag it (or I break yet more people).

There was an excellent episode of the Go Time podcast recently which talked about problems with v2 and modules.  Worth a listen IMO.  https://podcasts.google.com/feed/aHR0cHM6Ly9jaGFuZ2Vsb2cuY29tL2dvdGltZS9mZWVk/episode/Y2hhbmdlbG9nLmNvbS8yLzEzNjU?sa=X&ved=0CAUQkfYCahcKEwiQtZKi0qTyAhUAAAAAHQAAAAAQBg&hl=en
