### ISSUE TITLE
Is InfoLogger valuable?

### ISSUE THREAD

**Issue by thockin** [go-logr/logr#6]
If I pass you an InfoLogger, you can never log an error or use WithValues().  Is that a valuable restriction?   Or should V() just return a full Logger, and V(3).V(2).V(1) would be the same as V(6) ?

**Comment by thockin** [comment]
I thought about this more.  I think it is valuable as a contract, but it might be more valuable if we moved `V()` into it (and defined it as additive).

It might be more valuable yet if `WithValues()` was part of InfoLogger, but now we have a signature clash - should that return `InfoLogger` or `Logger`?

**Comment by DirectXMan12** [comment]
Practically, I've found numeric log levels to be frustrating to use.  The categories I usually reach for are "always", "sometimes", and "break my docker daemon".    k8s logging guidelines cover 1-5, practically k8s seems to use 1-10, and it's never quite clear what's appropriate.

I'm not quite sure what the counter-argument is though.  In an ideal wholistic logging system, semantic information plus standardized filtering would *probably* be easier to explain and use (e.g. this is trace-like, this is a request, and then by default filter out trace and request logs because they're guaranteed to be chatty), but I'm not certain how well that translates to all potential logging backends.

**Comment by DirectXMan12** [comment]
At the very least, it seems like tacking on `WithValues` to InfoLogger makes some amount of sense.

Separately from my above concerns, additive `V` sounds like a bit of a foot gun, and makes it difficult to log a critical error from from what looks like it might be a non-critical call (is that an intended feature?).

Attaching a severity to an error feels weirder to me at first glance.  What does it mean to have a severity 3 error?  Saying "this is an expected error", "this is a retryable error", etc feels more useful (again, semantic information).

**Comment by DirectXMan12** [comment]
(mostly these are from an "ideal world" perspective, though -- the practical reality is that V(x) is pretty entrenched in parts of the k8s ecosystem.  Other parts, like prow, don't use it at all, but do use semantic levels, like warning)

**Comment by thockin** [comment]
arbitrary V levels vs {INFO, WARN, ERROR} enumerated levels is really contentious, and while I am not dead set that V-levels are the best way, my experience with them has been overall better than with enumerated levels.  At least with V, you know more V == more logs, even if the exact numbers are a bit opaque

Part of the motivation for logr was the idea that WARNING is a bad idea - log lines are all INFO or ERROR.  But We know from experience that there are ACTUALLY grades of info.  Sometimes I want to know more and sometimes I don't need to.

In an ideal world we would log everything with metadata and let the tools thread it all together and filter noise, and it would cost no memory or IO bandwidth to do so.  In the real world, the tools are weak and it costs sigtnificant memory, CPU, and IO to log too much (and has been a source of problems for lots of people).

So I reject that WARNING is semantically meaningful, and I assert that there are grades of INFO.  I am loathe to try to name all the grades of info, lest we end up right back here arguing about what each named level means across projects.

Numbers have no semantic meaning other than order.  That's why I went with V levels.  I am open to debate, for sure, and I know there's many who disagree with me.  I could maybe buy that there's only INFO, ERROR, and TRACE, but I would assert that TRACE becomes the new V and need to become a spectrum again.

The thinking with V being additive is to put the power in the caller's hands.  Suppose I am using your library which also uses logr, and I find that your logs are interesting but not as interesting as my own logs.  I can pass you a Logger that is V(1), so your V(0) is my V(1).  It stands to reason that your V(1) should be my V(2), doesn't it? If you have a critical error, use Error() rather than Info(), which is not subject to V().  I did not mean that Error() would be levelled.

InfoLogger is a nice contract - if your lib takes an InfoLogger I know that it will never call Error().

WRT WithValues(), it's the return type that makes it hard.  We'd have to make 2 top-level interfaces and a way to convert between them.  Not the worst thing in the world, but more than simple duck typing.

**Comment by DirectXMan12** [comment]
> Part of the motivation for logr was the idea that WARNING is a bad idea 

Yeah, that part I still agree with, at least.  Warning is kinda silly -- was just enumerating what's out there in the above comment.

> I did not mean that Error() would be leveled

Ah, ok, I misinterpreted you there then :-)

**Comment by coryrc** [comment]
> The thinking with V being additive is to put the power in the caller's hands.

I like this because I believe in zapr, logr levels should map to -1*logrLevel+2 (i.e. V(0) == zap ErrorLevel, V(2) == zap InfoLevel; seems more consistent with klog V-levels, for example). With nested V(), it'd be trivial to use V(-2) to get my desired effect.

**Comment by winmillwill** [comment]
RE: whether `V` should return an object that doesn't implement `Error`, I feel like I should be able to get a logger for a component whose errors are interesting to me, but whose info logs are not. I also feel like a component that handles its own errors doesn't need to log them at all unless the code consuming that component is getting unexpected behavior and not getting an error, or it's getting an unclear error. This makes me think I should also be able to pass a fully muted logger. Moreover, I feel like an operator should be enabled to make these decisions based on what they do and don't see in the logs, and/or based on guidance from a maintainer.

I don't see any use case for seeing some level of info logs and not the errors, and I don't see errors as mandatory log entries because of component scope, so error messages don't seem like a different category to me... they're just the lowest level above mute.

I don't think handled errors are some level of info ... I think they're errors for some component, and that's orthogonal to whether an operator is interested in messages from that component. So, I would see an http client with a retrying middleware as a component distinct from the inner client, and I could be interested in whether there was an error at the top level, ie a non-retryable error or deadline or retries exhausted, and I may or may not also be interested in the particular errors associated with each attempt.
